### ISSUE TITLE
Identify cloud hosting service for hosting the Empirica server for deliberation

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#16]
As an experiment coordinator, I want to deploy my Empirica experiment to a cloud server that is cheap and can scale to larger volumes of users down the road, so that I can reliably conduct deliberation experiments using Empirica. 

Down the road, this service will want to interact with a statistical model runner, a participant manager/dispatcher, and a few other "microservices", so it may make sense to be in an environment that is conducive to that type of architecture.

@markwhiting, @sumants-dev - I know you've made a similar decision for the turk payments interface recently - can you help me understand how you made that choice?

@rivera-lanasm, @yli12313 - what is being used in the lab's other projects?

## Options:
- AWS Elastic Compute Cloud (EC2)
- AWS Elastic Container Service (ECS)
- AWS Elastic Beanstalk
- AWS Fargate
- Google App Engine
- others? (please add if we should consider something else!)

# Ready to close when:
- [ ] We have chosen a particular service/provider
- [ ] We have documented the reasons for that choice in this issue

**Comment by markwhiting** [comment]
Sorry, missed this. 

A big part of our decision was around technical restrictions imposed by some of the options. @sumants-dev likely has quite specific thoughts about these tradeoffs.

**Comment by sumants-dev** [comment]
The decision we made for turk-interface was driven by the following restrictions.
1.  Ability to connect to existing mongodb database
2.  Boto3 to communicate with mturk

These are things we tried, but didn't work.
1. elastic beanstalk (turk-interface), but it requires the databases to be an Sql RDS (we already had data in mongodb, and migrating would have been difficult).
2. app runner, but app runner currently only really supports connecting to AWS RDS, and restricts ability to connect to other amazon services. We couldn't connect to MTurk through Boto3. App Runner is new service, so they are still building out features. Only in January 2022 they allowed RDS connections. (I would love this service if just had better interoperability with other AWS services).

What we ended up with
1. an EC2 using Caddy (a server that does automatic https). 
This likely is fine for turk-interface as number connections at any point of time is likely less than 100.

What I recommend
Elastic beanstalk given that there is freedom using SQL database. It configures https for you, makes connection to your sql database, and any other networking configuration. Note that unlike App Runner, a CLI pipeline will need to be built and it's not automatically configured. Also I would recommend using elastic beanstalk with docker, so that the option to migrate to container service such as AWS fargate is easy.

**Comment by rivera-lanasm** [comment]
Hi Sumant, thanks for the summary! James looped me in here on Tuesday. I'll read into this

**Comment by JamesPHoughton** [comment]
For empirica V2, there is no external database, I believe it stores things in flat files on the server itself. On the one hand this means that we don't have to worry about connecting to another service, but on the other, it means that we need to make sure we persist that data when we stop and restart a session. 

I'm glad to hear you also think EB with docker is a good strategy. Yesterday I messed around with setting up a CD pipeline [here](https://github.com/Watts-Lab/deliberation-empirica/actions/workflows/deploy.yml). I think I have the permissions and general pieces in place. I still need to work out how to get Empirica V2 to work properly - it has a funny package structure.

**Comment by sumants-dev** [comment]
This might be helpful to locally set up github actions. I've used it and speeds up testing feedback loop.
https://github.com/nektos/act

**Comment by JamesPHoughton** [comment]
We've made enough progress with Elastic Beanstalk (here: https://github.com/Watts-Lab/deliberation-empirica/issues/11) that I expect it will be our solution for at least the summer. Closing this as a public act of commitment, although we can reopen if necessary. 🤓
