### ISSUE TITLE
🏃🏽‍♂️Internal test with WBL staff

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#364]
Purposes: 
- Demo our setup, check how it works with WBL setup
- Ask about our wording in the instructions, use fresh eyes to check about detail vs parsimoniousness

Our running todo-list is here:
https://github.com/orgs/Watts-Lab/projects/19/views/1

**Comment by JamesPHoughton** [comment]
- [E.R.] In the past, haven't needed to let people know what the topic of the discussion is. Just so long as people know they can leave if they want to do so.

- 60 second countdown at the end means you're tempted to close your browser

## Feedback From Emily's group:
- “Question-Structured Discussion” is weird — could it be just “Structured Discussion?”
Is there any way to warn people that the change / chime is happening? Or give them a reminder? I have no idea how long each discussion phase is, and by the time I hear the chime, it’s too late to click something
It could be good to have some kind of progress bar to show where people are throughout the discussion --- how many stages are left? Where are they in the big picture?

- We do see that when we hear the chime, the question has changed, but it is not super obvious --- you sort of have to actively pay attention to it, and it remains somewhat easy to miss
- There should be something visual to draw your eye to the side panel in addition to the audio chime e.g., a little bit of color, movement, or both --- especially because the top half of the panel remains static
- For the first few times, we heard the chime and were not sure what “caused” it
- Why is there an extra minute at the end of the discussion (is it to say goodbye?)
If people leave during the ‘goodbye’ period, will they miss the post-survey? (this could be a risk)

## discussion
- Unclear what we're supposed to be doing at the outset. Maybe a "map" to the experiment as a whole.
- Does it make sense that the question is open during the whole discussion window? Maybe need the submit button on the question.

**Comment by RachelAbigail** [comment]
Comments/feedback: 
- Change invitation email to a headings with bullet points structure
- In platform instructions, change "Question-Structured Discussion" to just "Structured Discussion"
- Need to make new questions more obvious as they pop up. The chime is super helpful but having something visual that draws your eye there would be good (e.g. question zooms in from the right, question text is in a different color, background behind the question and answer options is lightly highlighted in a color, etc.)
- Platform instructions ask you to answer each question before discussing, but right now it's structured so you can answer the question at any point during the allotted discussion time, and a participant could change responses during the discussion. Perhaps add a submit button here so answers are fixed.
- Leave button is def a good idea. Didn't need the whole extra minute to wind down.
- Add an overall status/progress bar so you know where you are in the overall discussion flow.

**Comment by xehu** [comment]
**Attempt to prioritize the different issues and suggestions**

1. **Invitation Email**
Change invitation email to a headings with bullet points structure

2.1 **Figuring Out What's Going On**
ambiguity between questions about self and other persons' perspectives. Separate page for questions about the opinions of other people in your group.
Unclear what we're supposed to be doing at the outset. Maybe a "map" to the experiment as a whole.

2.2 **Overall Progress Bar / Better Signposting / Live Agenda**
Add an overall status/progress bar so you know where you are in the overall discussion flow.
It could be good to have some kind of progress bar to show where people are throughout the discussion --- how many stages are left? Where are they in the big picture?

3. **Wording Changes**
In platform instructions, change "Question-Structured Discussion" to just "Structured Discussion"
“Question-Structured Discussion” is weird — could it be just “Structured Discussion?”

4. **Making Transitions / Questions Obvious — Chime is Not Enough**
Need to make new questions more obvious as they pop up. The chime is super helpful but having something visual that draws your eye there would be good (e.g. question zooms in from the right, question text is in a different color, background behind the question and answer options is lightly highlighted in a color, etc.)
Is there any way to warn people that the change / chime is happening? Or give them a reminder? I have no idea how long each discussion phase is, and by the time I hear the chime, it’s too late to click something
We do see that when we hear the chime, the question has changed, but it is not super obvious --- you sort of have to actively pay attention to it, and it remains somewhat easy to miss
There should be something visual to draw your eye to the side panel in addition to the audio chime e.g., a little bit of color, movement, or both --- especially because the top half of the panel remains static
For the first few times, we heard the chime and were not sure what “caused” it
Don't know what has changed when there is a ding, so reread from the top... Maybe make the things that never change really explicit, so people don't need to reread things?
Movement, color, etc?
Countdown timer for when the prompt is about to change.

5. **Side Panel Questions: Timing, Ability to Change**
Platform instructions ask you to answer each question before discussing, but right now it's structured so you can answer the question at any point during the allotted discussion time, and a participant could change responses during the discussion. Perhaps add a submit button here so answers are fixed.
Does it make sense that the question is open during the whole discussion window? Maybe need the submit button on the question.
seems that the answers to prompt items change by scrolling over the buttons?

6. **Post-Discussion / Leaving**
Leave button is def a good idea. Didn't need the whole extra minute to wind down.
Why is there an extra minute at the end of the discussion (is it to say goodbye?)
If people leave during the ‘goodbye’ period, will they miss the post-survey? (this could be a risk)

7. **Technical Glitches**
A few technical glitches in the discussion - on reconnect didn't use the same devices selected. Went back to the default devices. Need to check that the settings selected in the video check are used in all the discussions.
People always seem to have technical issues getting in; how do we set up a tech support in case there are problems?
