### ISSUE TITLE
Create a dailyCheck function that runs on batch creation

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#557]
Create a function in meetingRoom.js that will be run when the batch is created. the function should create a new meeting room by calling the existing CreateRoom function, and check for any errors. Errors could be that the recording bucket is invalid, or that the credentials are missing, or any number of things. Await the CreateRoom function, and then call CloseRoom, again checking for errors.

If there are errors discovered, they should be printed to the console, and then the error should be raised, in a similar way to what we do when we check the treatment file.

This strategy has some advantages over checking the recording buckets directly through the aws API. Firstly, it means we don't have to access the AWS API, as we are not currently using it. Second, it means that we are checking explicitly for buckets that Daily has the right permissions to access, which is what we care about anyways, and so is a more valid test.

**Comment by gumillie222** [comment]
I'm passing `batch.id` as the `roomName` into `DailyCheck` because we don't have a room set up when creating batches. `DailyCheck` calls `CreateRoom` and `CloseRoom`, so any error discovered there should be logged in console. In the `CreateRoom` function, I added in some code that checks for invalid `videoStorageLocation` and throw an error.

**Comment by JamesPHoughton** [comment]
Complete in https://github.com/Watts-Lab/deliberation-empirica/pull/562 - creates and closes a room with the given videoStorageLocation on batch creation.
